from jinja2 import Environment, FileSystemLoader
import json
import pathlib
import sys

def escape_encoding_names(encodings):
    for encoding in encodings:
        encoding["name"] = encoding["name"].replace("-", "_")
    return encodings

def build_encodings(env, target_dir, download_dir):
    with open(download_dir / "encodings.json", "r") as infile:
        encodings = json.load(infile)

    # Merge the encoding blocks together 
    encodings = sum((block["encodings"] for block in encodings), [])

    encodings = escape_encoding_names(encodings)

    template = env.get_template("encodings.rs.jinja")
    autogenerated_code = template.render(encodings=encodings)

    with open(target_dir / "encodings.rs", "w") as outfile:
        outfile.write(autogenerated_code)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: {sys.argv[0]} [OUT_DIR] [DOWNLOAD_DIR]")
        exit(1)

    target_dir = pathlib.Path(sys.argv[1])
    download_dir = pathlib.Path(sys.argv[2])
    env = Environment(loader=FileSystemLoader("templates"))

    build_encodings(env, target_dir, download_dir)
