import sys
from jinja2 import Environment, FileSystemLoader
import json
import os
import pathlib

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: {sys.argv[0]} [OUT_DIR] [DOWNLOAD_DIR]")
        exit(1)

    target_dir = pathlib.Path(sys.argv[1])
    download_dir = pathlib.Path(sys.argv[2])

    with open(download_dir / "html_named_entities.json", "r") as infile:
        named_entities = json.load(infile)

    env = Environment(loader=FileSystemLoader("templates"))

    template = env.get_template("named_entities.rs.jinja")
    autogenerated_code = template.render(named_entities=named_entities)

    with open(target_dir / "named_entities.rs", "w") as outfile:
        outfile.write(autogenerated_code)
