#![feature(iter_intersperse)]

use std::{env, fs, io, path::Path};

use serialize::{
    json::{JsonDeserializer, JsonError},
    Deserialize,
};

const OBJECT_IDENTIFIERS_PATH: &str = "object_identifiers.json";

/// A Namespace as specified in the json file
#[derive(Deserialize, Clone, Debug)]
struct Namespace {
    digits: Vec<usize>,
    short_name: String,
    long_name: String,
    elements: Vec<Namespace>,
}

#[derive(Clone, Debug)]
struct ObjectIdentifier {
    digits: Vec<usize>,
    name: String,
}

#[derive(Debug)]
enum Error {
    IO(io::Error),
    Deserialization(JsonError),
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

impl Namespace {
    fn enum_variant_name(&self) -> String {
        let basename = if self
            .long_name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '.')
        {
            &self.long_name
        } else {
            &self.short_name
        };

        capitalize(basename).replace([' ', '-', '.', '/', '_'], "")
    }

    fn get_identifiers(
        &self,
        current_path: &mut Vec<usize>,
        identifiers: &mut Vec<ObjectIdentifier>,
    ) {
        if self.digits.is_empty() {
            // This is an alias - add only the children
            for element in &self.elements {
                element.get_identifiers(current_path, identifiers);
            }
        } else {
            current_path.extend_from_slice(&self.digits);

            // Add the object identifer for this namespace
            let identifier = ObjectIdentifier {
                digits: current_path.clone(),
                name: self.enum_variant_name(),
            };
            identifiers.push(identifier);

            // Add all its children
            for element in &self.elements {
                element.get_identifiers(current_path, identifiers);
            }

            // Remove the digits we added again
            current_path.truncate(current_path.len() - self.digits.len());
        }
    }
}

fn main() -> Result<(), Error> {
    // NOTE: Thanks to the openssl developers for collecting so many different
    //       object identifiers and their meaning in https://github.com/openssl/openssl/blob/master/crypto/objects/objects.txt
    //       Our "object_identifiers.json" is a cleaned up version of their file.
    //       (This note can't be in the json itself because json doesn't support comments :/)

    println!("cargo:rerun-if-changed={OBJECT_IDENTIFIERS_PATH}");

    let json = String::from_utf8(fs::read(OBJECT_IDENTIFIERS_PATH)?)
        .expect("html_named_entities.json contains invalid utf-8");
    let mut deserializer = JsonDeserializer::new(&json);
    let root_namespaces: Vec<Namespace> = Vec::deserialize(&mut deserializer)?;

    // Create a constant for every known object identifier
    let mut object_identifiers = vec![];
    let mut path = vec![];
    for namespace in &root_namespaces {
        namespace.get_identifiers(&mut path, &mut object_identifiers);
    }

    let enum_variants: String = object_identifiers
        .iter()
        .map(|identifier| identifier.name.as_str())
        .intersperse(",")
        .collect();

    let match_arms: String = object_identifiers
        .iter()
        .map(|identifier| format!("{:?} => Self::{}", identifier.digits, identifier.name))
        .intersperse(",".to_string())
        .collect();

    let to_digit_arms: String = object_identifiers
        .iter()
        .map(|identifier| format!("Self::{} => &{:?}", identifier.name, identifier.digits))
        .intersperse(",".to_string())
        .collect();

    let autogenerated_code = format!(
        "
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum ObjectIdentifier {{
            {enum_variants},
        }}

        #[derive(Clone, Copy, Debug)]
        pub struct UnknownObjectIdentifier;

        impl ObjectIdentifier {{
            pub fn digits(&self) -> &'static [usize] {{
                match self {{
                    {to_digit_arms}
                }}
            }}

            pub fn try_from_digits(value: &[usize]) -> Result<Self, UnknownObjectIdentifier> {{
                let identifier = match *value {{
                    {match_arms},
                    _ => {{
                        return Err(UnknownObjectIdentifier);
                    }}
                }};
    
                Ok(identifier)
            }}
        }}
        "
    );

    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("object_identifier.rs");
    fs::write(dest_path, autogenerated_code)?;

    Ok(())
}

impl From<io::Error> for Error {
    fn from(value: io::Error) -> Self {
        Self::IO(value)
    }
}

impl From<JsonError> for Error {
    fn from(value: JsonError) -> Self {
        Self::Deserialization(value)
    }
}
